name: Test

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
